# ============================================================================
# FACTORIAL EXPERIMENT TEMPLATE
# ============================================================================
# Use this template to create new factorial experiments
#
# Instructions:
#   1. Copy this file and rename it (e.g., my_factorial.yaml)
#   2. Update experiment_name and description
#   3. Define your factors and levels
#   4. Specify all experimental conditions
#   5. Define hypotheses and analysis plan
# ============================================================================

experiment_name: "my_factorial_experiment"  # CHANGE THIS
study_type: "factorial"

# ============================================================================
# FIXED PARAMETERS (Same across all conditions)
# ============================================================================

fixed:
  # Task
  task: "hypergrid"
  grid_size: [32, 32]

  # Add fixed parameters here
  # These stay constant across all experimental conditions

  # Seeds
  num_seeds: 5
  base_seed: 42

# ============================================================================
# FACTORIAL DESIGN
# ============================================================================

factors:

  # Factor 1: [RENAME THIS]
  factor1_name:
    description: "What does this factor represent?"
    levels:

      level1:
        label: "Level 1 Label"
        # Define parameters for this level
        parameter1: value1
        parameter2: value2

      level2:
        label: "Level 2 Label"
        parameter1: value3
        parameter2: value4

      # Add more levels as needed

  # Factor 2: [RENAME THIS]
  factor2_name:
    description: "What does this factor represent?"
    levels:

      level1:
        label: "Level 1 Label"
        parameter3: value5

      level2:
        label: "Level 2 Label"
        parameter3: value6

  # Add more factors if needed (3-way, 4-way, etc.)

# ============================================================================
# EXPERIMENTAL CONDITIONS
# ============================================================================
# List ALL combinations of factor levels
# For 2 factors with 2 levels each: 2 × 2 = 4 conditions
# For 2 factors with 3 levels each: 3 × 3 = 9 conditions
# For 3 factors with 2 levels each: 2 × 2 × 2 = 8 conditions

conditions:

  # Format: {factor1_level}_{factor2_level}[_{factor3_level}]

  - name: "condition1"
    factor1_name: "level1"
    factor2_name: "level1"
    # factor3_name: "level1"  # If 3-way factorial

  - name: "condition2"
    factor1_name: "level1"
    factor2_name: "level2"

  - name: "condition3"
    factor1_name: "level2"
    factor2_name: "level1"

  - name: "condition4"
    factor1_name: "level2"
    factor2_name: "level2"

  # Add all other combinations...

# ============================================================================
# METRICS
# ============================================================================

metrics:
  primary:
    - mode_coverage_entropy  # Main diversity metric
    - hypervolume  # Main quality metric
    - quality_diversity_score  # Composite

  secondary:
    - trajectory_diversity_score
    - preference_aligned_spread
    # Add other metrics as needed

# ============================================================================
# ANALYSIS PLAN
# ============================================================================

analysis:

  research_questions:

    rq1:
      question: "Does Factor 1 have a main effect?"
      test: "one_way_anova"
      factor: "factor1_name"
      metric: "mode_coverage_entropy"

    rq2:
      question: "Does Factor 2 have a main effect?"
      test: "one_way_anova"
      factor: "factor2_name"
      metric: "mode_coverage_entropy"

    rq3:
      question: "Is there an interaction between factors?"
      test: "two_way_anova"  # or three_way_anova
      factors: ["factor1_name", "factor2_name"]
      metric: "mode_coverage_entropy"
      interaction_term: "factor1_name:factor2_name"

  statistical_tests:

    - name: "factorial_anova"
      test: "two_way_anova"  # Update based on number of factors
      formula: "mce ~ C(factor1_name) + C(factor2_name) + C(factor1_name):C(factor2_name)"
      alpha: 0.05

    - name: "posthoc_factor1"
      test: "tukey_hsd"
      factor: "factor1_name"
      metric: "mce"

    - name: "posthoc_factor2"
      test: "tukey_hsd"
      factor: "factor2_name"
      metric: "mce"

  visualizations:

    - name: "interaction_plot"
      type: "interaction_plot"
      x: "factor1_name"
      y: "mce"
      hue: "factor2_name"
      save: "figures/interaction_plot.pdf"

    - name: "heatmap"
      type: "heatmap"
      pivot:
        index: "factor1_name"
        columns: "factor2_name"
        values: "mce"
      save: "figures/heatmap.pdf"

# ============================================================================
# HYPOTHESES
# ============================================================================

hypotheses:

  h1_main_factor1:
    statement: "Factor 1 has a significant main effect on diversity"
    prediction: "Level X > Level Y"
    rationale: "Why you expect this result"

  h2_main_factor2:
    statement: "Factor 2 has a significant main effect on diversity"
    prediction: "Level A > Level B"
    rationale: "Why you expect this result"

  h3_interaction:
    statement: "There is an interaction between Factor 1 and Factor 2"
    prediction: "Describe expected interaction pattern"
    rationale: "Why factors should interact"
    expected_pattern: "Describe what interaction plot should look like"

# ============================================================================
# COMPUTATIONAL RESOURCES
# ============================================================================

resources:
  # Calculate: (num_levels_factor1) × (num_levels_factor2) × num_seeds
  total_runs: 20  # UPDATE THIS (e.g., 2×2×5 = 20)
  estimated_time_per_run: "24 minutes"
  total_time_sequential: "8 hours"  # UPDATE
  total_time_parallel: "1 hour"  # UPDATE (with parallelization)

  recommended_parallelization:
    strategy: "condition_parallel"
    max_parallel: 10

# ============================================================================
# EXPECTED RESULTS
# ============================================================================

expected_results:

  scenario_no_interaction:
    description: "Factors have independent additive effects"
    best_combination: "best_level_factor1 + best_level_factor2"
    implication: "Use best from each factor independently"

  scenario_interaction:
    description: "Optimal level of one factor depends on the other"
    examples:
      - "Factor1=X works best when Factor2=A"
      - "Factor1=Y works best when Factor2=B"
    implication: "Need to consider factors together"

  best_case:
    condition: "condition_name"  # Which condition is expected to be best
    expected_mce: ">0.5"
    expected_qds: ">0.65"

# ============================================================================
# NEXT STEPS
# ============================================================================

next_steps:

  if_no_interaction:
    - "Select best level from each factor independently"
    - "Proceed to next factorial experiment"

  if_interaction_found:
    - "Investigate mechanism of interaction"
    - "Consider interaction in final model selection"
    - "Report as key finding in paper"

  paper_contribution:
    - "Novel finding about factor interaction"
    - "Practical guidelines for practitioners"
